export * from "./HomePage";
export * from "./ButonPage";
export * from "./FilterPage";
export * from "./CounterPage";
export * from "./PricingPage";
export * from "./StyleButtonPage";
export * from "./RandomNumPage";
export * from "./TasksPage";
export * from "./NotFoundPage";
